### ISSUE TITLE
Add different roles for Linux installer script 

### ISSUE THREAD

**Issue by ps4signedout** [CrowdStrike/falcon-scripts#88]
It would be nice to have different roles for the Linux installer script:

--install
--configure
--uninstall

as already available for Ansible: https://galaxy.ansible.com/CrowdStrike/falcon

**Comment by carlosmmatos** [comment]
@ps4signedout I've introduced the ability to install the sensor only without additional configuration/registration steps. Simply set the following env variable to true like so: `export FALCON_INSTALL_ONLY=true`

Going to close this issue because we are not going to be supporting the use of flags yet, as the main point of this install script right now is to install/register cid/and start the sensor to give a customer a starting point. Additional configurations can be handled right now by our Ansible, Puppet, and Chef CM tools, as well as other methods.
